// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: document.sql

package repository

import (
	"context"
	"time"
)

const insertDocument = `-- name: InsertDocument :one
INSERT INTO document (
    id, 
    document_name, 
    date_time, 
    original_link, 
    content
)
VALUES (
    uuid_generate_v4(),
    $1,
    $2,
    $3,
    $4)
RETURNING id, document_name, date_time, original_link, content
`

type InsertDocumentParams struct {
	DocumentName string    `json:"document_name"`
	DateTime     time.Time `json:"date_time"`
	OriginalLink string    `json:"original_link"`
	Content      string    `json:"content"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.DocumentName,
		arg.DateTime,
		arg.OriginalLink,
		arg.Content,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentName,
		&i.DateTime,
		&i.OriginalLink,
		&i.Content,
	)
	return i, err
}
