// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID           uuid.UUID `json:"id"`
	DocumentName string    `json:"document_name"`
	DateTime     time.Time `json:"date_time"`
	OriginalLink string    `json:"original_link"`
	HtmlContent  string    `json:"html_content"`
	Content      string    `json:"content"`
	DocLanguage  string    `json:"doc_language"`
}
