// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package repository

import (
	"context"
)

const listenForNewSpeechRecords = `-- name: ListenForNewSpeechRecords :exec
LISTEN new_record
`

func (q *Queries) ListenForNewSpeechRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, listenForNewSpeechRecords)
	return err
}

const notifyNewSpeechRecord = `-- name: NotifyNewSpeechRecord :exec
SELECT pg_notify('new_record', $1)
`

func (q *Queries) NotifyNewSpeechRecord(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyNewSpeechRecord, pgNotify)
	return err
}
